### ISSUE TITLE
Streaming through stdout

### ISSUE THREAD

**Issue by Tarang** [matryer/xbar#121]
Is it possible to stream stuff instead of rerunning a script every few seconds?

I have an implementation but all I see is 'BitBar ...'

Great project btw! I've been trying to write something like this for ages but always got stuck.

**Comment by matryer** [comment]
That's an interesting idea - so a single long running process. Hmmm.

**Comment by matryer** [comment]
... and thanks :)

**Comment by Tarang** [comment]
It might sound bad in terms of a being a long running process, but it can make things quite efficient.

Sometimes there is an overheard with the first request, here websockets can be used to stream data down and update it as it arrives.

**Comment by keithamus** [comment]
To spitball on a design for this: you could send a particular escape character to tell BitBar that this particular block of stdout has finished. Take for example the following script:

```bash
#!/usr/bin/env sh
COUNTER=0
count() {
  COUNTER=$((COUNTER+1));
  echo "$COUNTER"
  echo '---'
  echo "Some menu entry"
  echo "~~~"
}
while true; do
  count
  sleep 1
done
```

The output looks a little like this:

    1
    ---
    Some menu entry
    ~~~
    2
    ---
    Some menu entry
    ~~~
    3
    ---
    Some menu entry
    ~~~

The `~~~` tells BitBar to take everything above it, and since the last `~~~` and render that menu. In other words BitBar can keep the process alive, buffer up to the next  `~~~` and subsequently render the menu.

**Comment by iosdeveloper** [comment]
Implemented in #317. :)

**Comment by exside** [comment]
please merge this, I'm using this and it works, the ONLY issue I have is that somewhere is a memory leak, at least the way I'm using it, basically JavaScript/Deno connecting to a websocket, streaming data and console.log() updates in the BitBar format...over time Bitbar consumes several 100MB of memory (starting at around 5.5MB in my case), so I have to kill it and restart it every few days (it actually depends on how much data comes in). I suspect is some kind of issue with all the console.logs() accumulating in the background, I tried to console.clear() etc. with no success so far...

**Comment by shepazon** [comment]
I do like this idea. The ability for a script to just stay running and periodically send updated information to BitBar would really be a win, because it eliminates the overhead of spawning processes periodically, and it lets the plugin more easily maintain state across passes through its code (instead of having to stash its variables to a file every time it runs).

**Comment by shepazon** [comment]
FWIW, the BitBar-alike SwiftBar uses this approach to do streaming plugins. See https://github.com/swiftbar/SwiftBar/issues/118.
