### ISSUE TITLE
Columns, too?

### ISSUE THREAD

**Issue by whilei** [matryer/xbar#350]
My first idea when putting together the 😄 plugin was for the emojis to span columns as well as rows, which might lead to a more available and compact layout. Perhaps maybe possible?

(As it is now, you can render as many emojis per row as you'd want, but would have no way of differentiating a selection...)

**Comment by mm2270** [comment]
What is it you're looking for exactly? Can you possibly post a screenshot to show what the issue is, or what you'd like to see?

**Comment by irstacks** [comment]
Currently the "dimensions" of the bitbar menus are constrained to the Y-axis, as in just up-and-down. I'd love to be able to use the X-axis, too. Specifically with regard to user input, since I know you can _n_-number of characters in any given row, but would have no way of differentiating a click on the left vs the right. 

![img_3752](https://cloud.githubusercontent.com/assets/10228550/17186466/6852e854-5403-11e6-97b0-51800fd9667e.jpg)

**Comment by aharris88** [comment]
I think this would be good. Would columns make it possible to do something like this?
![screen shot 2016-12-16 at 10 03 03 am](https://cloud.githubusercontent.com/assets/3266363/21271139/ed2f08a4-c376-11e6-91bd-afe0694c5c6b.png)

**Comment by dimitrieh** [comment]
I am looking for this too..

```
#!/bin/bash
number=$(~/.dotfiles/bin/clustergit -q -C --warn-unversioned -d ~/projects;);
echo "✾ ${number}";
echo "---";
~/.dotfiles/bin/clustergit -q -H -R --warn-unversioned -d ~/projects;
```

with https://github.com/mnagel/clustergit 

it aligns nicely in the terminal, but in bitbar it misaligns the columns

**Comment by dimitrieh** [comment]
cc: @matryer

**Comment by jbnv** [comment]
I'm interested in columns as well. I modified the GeoIPWeather plugin to show the extended forecast. It works well, but it looks bad because stuff isn't lined up into columns.

**Comment by shepazon** [comment]
This would probably solve my problem that led me to file #605.
