### ISSUE TITLE
BitBar Environment Variable: Version Number

### ISSUE THREAD

**Issue by raguay** [matryer/xbar#358]
It would be nice for BitBar to set an environment variable for the current version of BitBar. That way, script can take advantage of feature in newer versions, but not break on older versions.

**Comment by iosdeveloper** [comment]
Added in [v2 beta 10](https://github.com/matryer/bitbar/releases/tag/v2.0.0-beta10).

**Comment by frakman1** [comment]
@iosdeveloper Thank you for adding this feature. I'm having trouble using it though. I'm using python code like this:

```python
envVer = str(os.environ['BitBarVersion'])
print "envVer is: " + (envVer)
```
...and getting `1` as the version.

UPDATE:
It turns out, I was getting the `Build` number instead of the actual `Version`. 
![image](https://user-images.githubusercontent.com/5826484/60349294-48aa3c80-998f-11e9-9224-a8c7048b42cd.png)

I looked into it and the key you are accessing is the one for `Build`. It should be:

```objective-c
env[@"BitBarVersion"] = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"];
```

instead of 
```objective-c
env[@"BitBarBuild"] = [[NSBundle mainBundle] objectForInfoDictionaryKey:(NSString *)kCFBundleVersionKey];
```

[reference](https://stackoverflow.com/a/7608711)
