### ISSUE TITLE
Go interpreted not working

### ISSUE THREAD

**Issue by cschlosser** [matryer/xbar#394]
Hello,

I tried to get a go script running with bitbar, but the interpreted version does not seem to work.

When I compile the go script everything is working perfectly fine but the interpreted version always displays this error in Bitbar for me:
<img width="244" alt="bildschirmfoto 2017-02-02 um 15 31 35" src="https://cloud.githubusercontent.com/assets/2466365/22553373/be9f8192-e95c-11e6-85d0-8404e0e4cc30.png">
 
I'm using BitBar 1.9.2.

Can be reproduced with the following code:
```go
//usr/bin/env go run $0 $@ ; exit

package main

import (
        "fmt"
)

func main() {
        fmt.Println("Test")
}
```

Is there anything I'm doing wrong?

**Comment by oleander** [comment]
The script needs to be executable as well, so try running `chmod +x myfile`
on it.

På 2 februari 2017 kl. 15:39:21, Christoph Schlosser (
notifications@github.com) skrev:

Hello,

I tried to get a go script running with bitbar, but the interpreted version
does not seem to work.

When I compile the go script everything is working perfectly fine but the
interpreted version always displays this error in Bitbar for me:
[image: bildschirmfoto 2017-02-02 um 15 31 35]
<https://cloud.githubusercontent.com/assets/2466365/22553373/be9f8192-e95c-11e6-85d0-8404e0e4cc30.png>

I'm using BitBar 1.9.2.

Can be reproduced with the following code:

//usr/bin/env go run $0 $@ ; exit
package main
import (
        "fmt"
)
func main() {
        fmt.Println("Test")
}

Is there anything I'm doing wrong?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/matryer/bitbar/issues/394>, or mute the thread

**Comment by christophschlosser** [comment]
I already did this.
The script is running fine when I'm executing it from the terminal.

**Comment by tresni** [comment]
The problem appears to be a lack of shebang (`#!`).  The comment isn't the same as a shebang and while that works under bash, it doesn't work under ZSH or normal sh.  It looks like NSTask launches in something like sh.  So NSTask can't use the starting line ala bash, there is no shebang to tell the sh what to do and so it errors out with the posix_spawn message.

Now, there is a workaround.  [gorun](https://github.com/erning/gorun) allows you to put shebang as the first line.  Install it with `go get  github.com/erning/gorun`. Then you just change the first line of your .go file to:

```
#! /usr/bin/env gorun
```

The thing to note is that it will no longer compile directly, you'd have to comment out the first line to compile the code.
