### ISSUE TITLE
Javascript / multifile / node_modules best practices?

### ISSUE THREAD

**Issue by dbuezas** [matryer/xbar#442]
Made a couple of plugins (jira and docker) in javascript and I have to "hide the code" in a different folder and load it from a single file in the bitbar-plugins folder to avoid bitbar interpreting the wrong files.
Is there any best practice for that? I'd love to publish the plugins, but I don't know how to handle this problem. 

here is the repo
https://github.com/dbuezas/jira-for-bitbar

**Comment by luoweihua7** [comment]
same question.
It's there any way to ignore file just like `.gitignore`

**Comment by dbuezas** [comment]
@luoweihua7 I found this approach, may be useful for you also:
https://github.com/whitepages/bitbar-docker

```javascript
$ npm install -g bitbar-docker
$ ln -s $(which bitbar-docker) bitbar-docker.10s.js
```

**Comment by aengl** [comment]
Also ran into this issue. Ideally I'd just like to have a `package.json` in the bitbar directory.

I think having an ignore file (`.bitignore`? 😁 ) would be the best solution.

**Comment by garyking** [comment]
I'm not sure what the problem is? I have about 10 plugins, all written in JS, and I point BitBar directly to that plugins dir.

They are all `chmod +x` and have the contents like:

```js
#!/usr/local/bin/node
console.log('test')
```

**Comment by aengl** [comment]
@garyking The problem is not with the scripts themselves, they run fine. But in the NPM ecosystem, the recommended and canonical way to install dependencies is by using a [package.json](https://docs.npmjs.com/files/package.json) file to specify the dependencies and their versions .

`bitbar` will interpret this file as a script and try to run it, which will show up as an unwanted entry in the menu bar.

It would probably be a reasonable default behaviour to ignore data files (`.json`, `.yaml`, `.txt`, etc.) in general.

**Comment by garyking** [comment]
Indeed, so that's why I have the package file in my project's root
directory, then put the scripts in a subdirectory, then I don't have this
problem. I just point BitBar to my plugin subdirectory, then it never even
sees the package file.

**Comment by aengl** [comment]
@garyking Smart! Thanks for the explanation, that's a good workaround. I will do the same.
