### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by BigPrimeNumbers** [matryer/xbar#464]
When selecting "Check for Updates" from the BitBar dropdown menu, I get an update error:

![image](https://user-images.githubusercontent.com/3743463/37798340-8b0dfb0c-2dc0-11e8-839d-9700caa4b3c3.png)

I am on the latest version of BitBar (1.9.2), running on MacOS 10.13.3 (17D102), and currently only use one plugin:
Weather by Daniel Seripap

**Comment by byaruhaf** [comment]
I have the same error

**Comment by gingerbeardman** [comment]
It's probably due to this: https://githubengineering.com/crypto-deprecation-notice/

But there's no new release/version anyway, and it seems unlikely there will be one soon.

**Comment by abraham** [comment]
This is still an issue.

**Comment by alexandregz** [comment]
There are two problems: first, Sparkle is too old and, second, URL used to update don't works -and is hardcoded: https://github.com/matryer/bitbar/blob/master/App/BitBar/AppDelegate.m#L36-L39

I created a release with a "new" version (v1.9.3) resolving these problems, because I see that project is abandoned 😞 

https://github.com/alexandregz/bitbar/releases/tag/1.9.3
