### ISSUE TITLE
What's the default font used by BitBar?

### ISSUE THREAD

**Issue by garyking** [matryer/xbar#521]
What is the default used by BitBar in the MacOS Mojave menu bar? I am trying to figure it out, by going through several `SF Pro` (San Fransisco) fonts as [provided by Apple](https://developer.apple.com/fonts/), but none match perfectly. The closest I found is `SF Pro Text Regular`, but the vertical spacing is greater in that font, than it is with the default one.

**Comment by neuronsong** [comment]
I'm using bitbar with the Catalina Beta, btw. Works great. I've just started using this and it really works great for what I want to do.

I'm curious about the font as well. I'd like to be able to set a specific font. It is the case I output a number of lines of txt and I'd like the font to be fixed width to have the output show up aligned the way it does in my terminal:

Here's an example of the output... which comes out skewed with a variable width font. Replace the '*' with '+' and the following becomes quite skewed. I switched to using '*' instead of '+' because there is less width difference between '*' and '-'.

[-****--*--] [ 50%] [biz]
[-***--*---] [ 40%] [dev]
[-****-----] [ 40%] [gam]
[****--*---] [ 50%] [okr]
[**********] [100%] [per]
[--**------] [ 20%] [wrk]

Currently when each line appears it shifts everything to the left of it in the bar just slightly... back and forth. This can be visually distracting... which is handy if done on purpose... but annoying if not.

**Comment by gingerbeardman** [comment]
Two answers.

Not sure about system font, but to get what you want you would need to use the monospaced version of it.

**Comment by neuronsong** [comment]
So the system font is being used. You are not setting a font directly.
Are there plans to change this so a user can set a specific font?

**Comment by gingerbeardman** [comment]
@neuronsong you can already set a specific font  
https://github.com/matryer/bitbar/blob/master/README.md

**Comment by neuronsong** [comment]
Thank you! I missed that. That works just fine.
