### ISSUE TITLE
How to get this working with TypeScript?

### ISSUE THREAD

**Issue by garyking** [matryer/xbar#548]
Anyone know how to get BitBar to run a TypeScript file (.ts), without needing to convert it to JS first? Using `ts-node`?

I tried the following, in `test.10s.ts`, with `chmod +x`:

```ts
#!/usr/bin/env /usr/local/bin/ts-node
console.log('Test');
```

But it gives the error in BitBar: `env: node: No such file or directory`.

**Comment by nicolas-b12** [comment]
Try this : `#!/usr/bin/env -S node -r "ts-node/register"`

**Comment by garyking** [comment]
Nope sorry, same error of `env: node: No such file or directory` in BitBar, and when run in Bash with `./test.10s.ts`, I get: `Error: Cannot find module '"ts-node/register"'` 

My `ts-node` is located at `/usr/local/bin/ts-node`.

**Comment by nicolas-b12** [comment]
What does `which node` outputs ?

**Comment by garyking** [comment]
`which node` outputs `/usr/local/bin/node`

**Comment by nicolas-b12** [comment]
Does it work if you compile the ts file down to js and use node as shebang ?

**Comment by garyking** [comment]
Yep that definitely works. I've been doing that for a while now. I convert from TS to JS, then in the JS, it's this:

```js
#!/usr/local/bin/node
console.log('Test');
```

**Comment by nicolas-b12** [comment]
Does running the Typescript with shebang as a shellscript works ?

**Comment by garyking** [comment]
Nope, like I said, I get the error `Error: Cannot find module '"ts-node/register"'` when run with `./test.10s.ts`.

**Comment by nicolas-b12** [comment]
Yes but with the shebang /usr/bin/env ts-node ?

**Comment by garyking** [comment]
For `test.1m.ts`, the contents are:

```ts
#!/usr/bin/env ts-node
console.log('test');
```

When run in BitBar, the error is: `env: ts-node: No such file or directory`

And when run in the shell, with `./test.1m.ts`, the output is: `test`.

When using the full path to `ts-node`, I get the error as mentioned in the first post of this thread.

**Comment by szhu** [comment]
Alternatively, consider [Deno](https://github.com/denoland/deno), an upcoming ts/js runtime from the creator of Node. I've been using it with BitBar and it works great!

`brew install deno`, then put this in your script:

```ts
#!/usr/bin/env deno
console.log('Test');
```

Happy to help if you have questions about Deno!

(Note: I have no affiliation with the Deno project but I think it's cool and I'm starting to use it here and there in small scripts.)

**Comment by garyking** [comment]
I'm only vaguely familiar with Deno. My BitBar scripts are complex; they aren't just a simple `console.log`, but instead import other user modules, which in turn, import Node modules. I assume I'd have to change these imports to URL imports for Deno, for instance. So unfortunately, I can't just easily switch to it.

**Comment by szhu** [comment]
Ah thanks for the clarification.

Looking at the original error message then:

> `env: node: No such file or directory.`

Where is the path to `node`? Is it `/usr/local/bin/node`? Can you try making your script this instead?

```sh
#!/bin/sh

export PATH="/usr/local/bin:$PATH"
ts-node path/to/script.ts
```

**Comment by exside** [comment]
@szhu saw it by accident, but also working with deno and bitbar =), deno rocks! I don't think it is deno related because my script works perfectly in bash, but I can't get it to display anything (only seeing the ... in the menubar forever)... what am I doing? Trying to basically display updates I receive from a websocket connection but not really knowing the inner workings of bitbar I suspect that because the script basically never finishes (as it receives constant updates) it never displays something? Any help is appreciated =), here's the code:

```js
#!/usr/bin/env /usr/local/bin/deno run --allow-net

import {
  connectWebSocket,
  isWebSocketCloseEvent,
  isWebSocketPingEvent,
  isWebSocketPongEvent,
} from 'https://deno.land/std/ws/mod.ts';

const endpoint = Deno.args[0] || 'wss://<endpoint>/realtime';


try {
  let current = null;
  let last = null;

  const sock = await connectWebSocket(endpoint);
// subscribe to ws topic
  await sock.send('{"op":"subscribe","args":["<topic>"]}');

  const messages = async () => {
    for await (const msg of sock) {
      if (typeof msg === 'string') {
        const response = JSON.parse(msg);

        if ( Array.isArray(response.data) ) {
          // only use the last item in the data array
          current = response.data.pop().price;
          
          // only print output when data changes
          if ( last != current ) {
            last = current;
            console.log(`${last}`);
            // also tried combinations like this, to no avail
            console.log(`${last} | terminal=true | refresh=true`);
          }
        }

      } else if (isWebSocketPingEvent(msg)) {
        //console.log('< ping');
      } else if (isWebSocketPongEvent(msg)) {
        //console.log('< pong');
      } else if (isWebSocketCloseEvent(msg)) {
        throw new Error(`closed: code=${msg.code}, reason=${msg.reason}`);
      }
    }
  };

  await Promise.race([messages()]).catch(console.error);

  if (!sock.isClosed) {
    await sock.close(1000).catch(console.error);
  }
} catch (err) {
  throw new Error(`Could not connect to WebSocket: '${err}'`);
}

Deno.exit(0);
```

see anything I'm missing?

**Comment by stefandesu** [comment]
Since I might not be the only one finding this thread: I had trouble executing a JavaScript file because I got the same error as @garyking above (`env: node: No such file or directory` when using `#!/usr/bin/env node`). 

The example given by @szhu with `#!/usr/bin/env deno` gave the same error, but also didn't work via the terminal. I then tried `#!/usr/bin/env -S deno run` which worked on the terminal, but xbar showed the same error again. The only solution that worked for me was:

```js
#!/usr/local/bin/deno run
console.log("Test")
```

This, of course, depends on Deno being available in `/usr/local/bin/` (which should always be the case when installed via Homebrew though). If there's a better solution that uses `/usr/bin/env`, please let me know!

**Comment by szhu** [comment]
Oh right. At some point in the past year, before Deno reached 1.0, the shortcut `deno my-script.ts` was removed, and now you have to run scripts using `deno run my-script.ts`. The change was recorded here: https://github.com/denoland/deno/issues/4701

So then, the solution is to have:

```ts
#!/usr/bin/env deno run
console.log("Test")
```

I tried it and it seems to work!

Note that having more than two args in the shebang line is not portable, it works on BSD (including macOS) but doesn't work on Linux: https://unix.stackexchange.com/questions/63979 Obviously not an issue here since xbar is a Mac app, but good to know in case you work with Linux in the future.

**Comment by its-dibo** [comment]
if you are using ESM, try this

```
#!/usr/bin/env -S node --loader ts-node/esm
```
or

```
#!/usr/bin/env -S node --loader ts-node/esm --experimental-specifier-resolution=node --experimental-import-meta-resolve --no-warnings
```

if you are using `eslint-plugin-n`, you need to disable this option for this file **below** the shebang syntax
```
#!/usr/bin/env -S node --loader ts-node/esm 
/* eslint-disable n/shebang */
```

**Comment by linusjf** [comment]
Encountered the same problem with ts-node. Fixed it by using pnpm instead to install ts-node on Termux. But this is strange. It worked earlier on Termux using node, I think.

<https://github.com/linusjf/LearnJavaScript/tree/main/TypeScript>

Been a while since though.. Right now, just need to see ts-node working.

<https://github.com/linusjf/LearnTypeScript>

**Comment by garyking** [comment]
This is for future reference. 

I use `tsx` to run my `.ts` files. I place the following line at the top of my xbar plugin, and it worked: `#!/usr/bin/env tsx`
