### ISSUE TITLE
Keeps losing position in menu bar

### ISSUE THREAD

**Issue by austengary** [matryer/xbar#565]
This is still broken / happening to me

_Originally posted by @austengary in https://github.com/matryer/bitbar/issues/480#issuecomment-650606139_

**Comment by frakman1** [comment]
@austengary I think this is only implemented in the beta release/branch. Did you try that?

**Comment by x-ji** [comment]
Seems to me that the position is lost after waking up from sleep. The BitBar output always gets shoved to the leftmost position (and becomes hidden due to there being a huge number of menubar icons already). In the linked issues there didn't seem to be a solution.

**Comment by minamotorin** [comment]
I have same issus after sleep in v1.10.1. I want to update. But I have two workarounds.

The first idea is using [this build](https://github.com/matryer/bitbar/pull/502#issuecomment-597561941). But this seems not maintained.

The second one is using defaults command, command line macOS configuration tool. Set the BitBar item where you want in menu bar and run ` % defaults read com.matryer.BitBar | grep '"NSStatusItem Preferred Position Item-' `. Add ` defaults write com.matryer.Bitbar "NSStatusItem Preferred Position Item-${Item_Number}" ${Position_Number} ` to your scrigt as shell commad. An example is shown below:

```
% defaults read com.matryer.BitBar | grep '"NSStatusItem Preferred Position Item-' 
    "NSStatusItem Preferred Position Item-0" = "13.13";
    "NSStatusItem Preferred Position Item-1" = "666";
% sed -i"" -e '$a\
defaults write com.matryer.BitBar "NSStatusItem Preferred Position Item-1" 666\
' /pass/to/your/script.sh
```

It work after defaults command running after sleep. So there are time lag until BitBar itmes repositioned since sleep.

**Comment by minamotorin** [comment]
Or the third, you can use [SwiftBar](https://github.com/swiftbar/SwiftBar). I found this after write the comment above.
