### ISSUE TITLE
posix_spawn error 1

### ISSUE THREAD

**Issue by JonLaliberte** [matryer/xbar#572]
I just wanted to share this in case it saves someone else some trouble.

I was receiving this error when trying to run a php script with BitBar.
The script was executable, and had the shebang "#!/usr/bin/php".
I noticed it wouldn't execute in terminal either.
For some reason in zsh I wasn't getting a useful error (forgive me if I'm missing something, first day with zsh was today), but in bash I was able to get this error "/usr/bin/php: bad interpreter: Operation not permitted".

This lead me to: https://fvdm.com/code/fix-for-bad-interpreter-operation-not-permitted

Which says to run `xattr -d com.apple.quarantine path/to/script`

This fixed it!

**Comment by JonLaliberte** [comment]
A short time later, this error happened again. Running the command again fixed it.
I also came across this: https://superuser.com/questions/1542429/com-apple-quarantine-is-everywhere-how-do-i-stop-it which may be relevant.

**Comment by ApopheniaPays** [comment]
`xattr -d com.apple.quarantine path/to/script` does nothing except change the error from "posix_spawn: error 1" to "posix_spawn: error 2".

I have a very important Bitbar bash script that took forever to write and get debugged i have relied on for months. Today I made a very minor change to one line of it, and now it has stopped opening in Bitbar, with the "posix_spawn" error. Prior to running `xattr -d com.apple.quarantine path/to/script`, aftr the "posix_spawn" error began, the script ran in terminal just fine. Since then, though, nothing at all happens when I run it in terminal. It's as if I didn't run it at all, I just get another command prompt. It's like it's just plain ignoring my input.

I also tried `chmod +x /path/to/script`, which also did nothing.

I am dead in the water now, this is a script I _NEED_. I used it dozens of times a day for months, until about 30 minutes ago. Please help.

**Comment by ApopheniaPays** [comment]
Ok, if anybody comes here looking for a solution, here's what it turned out to be. 

I use BBedit to edit my shell scripts. Turns out, there is a setting somewhere in BBedit, which I absolutely can't find, that automatically converts all line endings to DOS every time you open a file and automatically saves it. This causes the posix_spawn error, and it can happen if you so much as open a file in BBedit, you don't even have to save it. All my settings in the app say to use Unix line endings and it doesn't make a difference.

The solution for me was to use a command line app called dos2unix that converts files to the proper Unix line endings. I don't recall where I got it but if you google you should be able to find it, I might've installed it with Homebrew. Every time I open a Bitbar script in BBedit, I now must run it through dos2unix for Bitbar to be able to run it without the posix_spawn error. Hardly ideal, but it's a solution that worked when the others on this page didn't for me.
