### ISSUE TITLE
How do you install the main app?

### ISSUE THREAD

**Issue by peterbe** [matryer/xbar#654]
I downloaded the latest `.dmg` which today was [v2.0.32-beta](https://github.com/matryer/xbar/releases/tag/v2.0.32-beta)
Dragged it into my "Applications" folder like any other app. Then I open Finder and find it in there in "Applications". 
Double-clicking doesn't do anything. Pressing ⌘-o doesn't do anything. 

No `~/Library/Application Support/xbar*` directory is created. 

I tried pressing the "Open in xbar app" on a page like this: https://xbarapp.com/docs/plugins/Web/cornify.1m.sh.html
<img width="526" alt="Screen Shot 2021-03-19 at 4 36 32 PM" src="https://user-images.githubusercontent.com/26739/111839529-4f9a8080-88d1-11eb-8024-91cc42898334.png">

But this...
<img width="372" alt="Screen Shot 2021-03-19 at 4 36 36 PM" src="https://user-images.githubusercontent.com/26739/111839557-59bc7f00-88d1-11eb-900a-131eb8442e8e.png">

My OS is here:

<img width="698" alt="Screen Shot 2021-03-19 at 4 37 19 PM" src="https://user-images.githubusercontent.com/26739/111839571-617c2380-88d1-11eb-86b1-8d5fdf98f924.png">

**Comment by magicus** [comment]
Can you cmd-click the xbar app and select "Open" in the menu? Due to restrictions in macOS, just double clicking (or apparently opening using a URL) will not allow you to override the default restrictive security measures. (If you are cynical, you'd view this as a way from Apple to milk developers of money)

However, the expected result of doubleclicking xbar would be to get the "cannot open" dialog, not that nothing happens...

**Comment by nicolasff** [comment]
Yes, right-click the app and select "Open". You need to do this the first time because it's not a signed app you downloaded from the app store, but just an app downloaded from GitHub. You will then need to confirm you want to run it, and if you do you'll then be able to start it as any other app from then on. You just need to do this the first time.

Here is the Apple Support page explaining this process: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

![image](https://user-images.githubusercontent.com/7276/111853928-187c9d00-88da-11eb-8fc5-2e4b2557b278.png)

**Comment by matryer** [comment]
@peterbe eventually I hope to get this fixed, but for now try @magicus' approach, or right click and choose **Open** and it should work. (You'll only need to do this the first time).

**Comment by peterbe** [comment]
Cheers. That did work.
