### ISSUE TITLE
xBar widgets move by themselves when using Vanilla

### ISSUE THREAD

**Issue by entreprenewer** [matryer/xbar#711]
When using Vanilla for organizing the menu bar (https://matthewpalmer.net/vanilla/), xBar-related widgets always move to hidden all the way on the far left. All other icons stay just fine, but xBar seems to not work properly. 

I suspect this is happening b/c xBar is loading after Vanilla on startup. Any ideas on how to fix?

**Comment by leaanthony** [comment]
I've got no suggestions, sorry.

**Comment by magicus** [comment]
FWIW, I'm having similar (and probably related) problems with Bartender and xbar. Previously, I used [Dozer](https://github.com/Mortennn/Dozer), and BitBar, and that did not work at all. What did work, was a special, patched build of BitBar.

One comment (https://github.com/Mortennn/Dozer/issues/47#issuecomment-477952653) suggest that this was since "when BitBar refreshes, it destroys all menu bar icons and then rebuilds them."

In general, I think xbar plays much more nicely with menu bar hider/reshufflers, but it's not perfect. I still have to reshuffle my xbar icons from time to time, but I have not really been paying attention to when it happens. I think it is only when xbar has updated, but I'm not sure. It might be after a full reboot as well.

**Comment by leaanthony** [comment]
Xbar does indeed refresh existing menus rather than destroy them. If you have any insights into making it even better, we're all ears 😃

**Comment by magicus** [comment]
Unfortunately I don't have any deeper insights in macos APIs. :( I'm just thinking about the update scenario: are menu items described with some kind of unique identifier? Might this be changed during updates?

**Comment by magicus** [comment]
@entreprenewer Have you tried opening a bug on Vanilla for this? It might be that the fault (or at least the only possible fix) lies entirely with Vanilla, or with xbar, or with both of them in concert.

**Comment by matryer** [comment]
Closing this because I don't think we can help. :(

**Comment by entreprenewer** [comment]
Oops just saw that this was closed - I forgot I'd opened it and opened a new one again today - my bad. 
I did send Vanilla a message... no responses, as usual.
